application/bro/models.py
from datetime import datetime, date

from flask_bcrypt import generate_password_hash, check_password_hash
from flask_login import UserMixin, AnonymousUserMixin
from application.main.extensions import db, login_manager
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import relationship

BCRYPT_LOG_ROUNDS = 12


@login_manager.user_loader
def get_user(bro_id):
    return Bro.query.get(int(bro_id))


class AnonymousBro(AnonymousUserMixin):
    def __init__(self):
        self.id = 0


friendship = db.Table('friendships', db.Model.metadata,
                      db.Column('bro_id', db.Integer, db.ForeignKey('bros.id', ondelete='cascade')),
                      db.Column('friend_id', db.Integer, db.ForeignKey('bros.id', ondelete='cascade')),
                      db.UniqueConstraint('bro_id', 'friend_id', name='unique_friendships'))


class Bro(db.Model, UserMixin):
    __tablename__ = "bros"

    id = db.Column('id', db.Integer, primary_key=True)
    username = db.Column('username', db.String(60), index=True)
    email = db.Column('email', db.String(255), unique=True, index=True)
    _password = db.Column('password', db.String(255))
    registered_on = db.Column('registered_on', db.DateTime, default=datetime.utcnow())
    birthdate = db.Column('birthday', db.DateTime)
    active = db.Column('is_active', db.Boolean, default=True)
    best_friend_id = db.Column(db.Integer, db.ForeignKey('bros.id', ondelete='SET NULL'))
    best_friend = relationship('Bro',
                               uselist=False,
                               remote_side=[id],
                               post_update=True
                               )

    friends = relationship('Bro', secondary=friendship,
                           primaryjoin=id == friendship.c.bro_id,
                           secondaryjoin=id == friendship.c.friend_id)

    @hybrid_property
    def password(self):
        return self._password

    @password.setter
    def _set_password(self, plaintext):
        self._password = generate_password_hash(plaintext, BCRYPT_LOG_ROUNDS)

    def is_active(self):
        return self.active

    def __str__(self):
        return self.username

    def __repr__(self):
        return "<Bro username=%s>" % self.username

    def get_id(self):
        return unicode(self.id)

    def is_correct_password(self, plaintext):
        return check_password_hash(self._password, plaintext)

    @property
    def age(self):
        today = date.today()
        born = self.birthdate
        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

    def befriend(self, bro):
        if not self.is_same_bro(bro) and bro not in self.friends:
            self.friends.append(bro)
            bro.friends.append(self)

    def unfriend(self, bro):
        if not self.is_same_bro(bro) and bro in self.friends:
            self.friends.remove(bro)
            bro.friends.remove(self)

    def is_best_friend_with(self, bro):
        return self.best_friend == bro

    def add_best_friend(self, bro):
        if not self.is_best_friend_with(bro):
            self.best_friend = bro
            bro.best_friend = self

    def remove_best_friend(self, bro):
        if self.is_best_friend_with(bro):
            self.best_friend = None
            bro.best_friend = None

    def is_same_bro(self, bro):
        return self.id == bro.id

    def is_friend(self, bro):
        return True if bro.id in [friend.id for friend in self.friends] else False

    @property
    def friends_qty(self):
        return len(self.friends) + (1 if self.best_friend else 0)

application/bro/forms.py
from application.bro.models import Bro
from flask_wtf import Form
from wtforms import PasswordField, StringField, DateField, BooleanField
from wtforms.validators import InputRequired, DataRequired, Email, EqualTo


class BaseForm(Form):
    email = StringField('Email', [Email()])

    def validate_for_exist(self, current_bro=None):
        rv = Form.validate(self)
        if not rv:
            return False

        if not current_bro and self._get_bro_by_email(self.email.data):
            self.email.errors.append("Bro with this email exists")
            return False

        bro = self._get_bro_by_email(self.email.data)
        if bro and current_bro and bro.get_id() != current_bro.get_id():
            self.email.errors.append("Bro with this email exists")
            return False
        return True

    @staticmethod
    def _get_bro_by_email(email):
        return Bro.query.filter_by(email=email).first()


class SignInForm(Form):
    email = StringField('Email', [InputRequired()])
    password = PasswordField('Password', [InputRequired()])
    remember = BooleanField('Remember me?')


class SignUpForm(BaseForm):
    username = StringField('Username', [DataRequired()])
    password = PasswordField('Password', [InputRequired(), EqualTo('confirm', message='Passwords must match')])
    confirm = PasswordField('Confirm Password', [InputRequired()])
    birthdate = DateField('Birth Date', [InputRequired()], format='%m/%d/%Y')


class EditForm(BaseForm):
    username = StringField('Username', [DataRequired()])
    birthdate = DateField('Birth Date', [InputRequired()], format='%m/%d/%Y')


class DeleteForm(Form):
    pass

application/bro/__init__.py
from .views import bro

application/bro/views.py
from application.bro.forms import SignInForm, SignUpForm, DeleteForm, EditForm
from application.bro.models import Bro
from application.bro.sort_strategy import SortStrategy
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, logout_user, current_user, login_required
from flask_paginate import Pagination
from application.main.extensions import db
from application.main.utils import current_user_exists, redirect_url

BROS_PER_PAGE = 12

bro = Blueprint('bro', __name__)


@bro.route('/')
def index():
    return render_template('bro/index.html')


@bro.route('/signin', methods=['GET', 'POST'])
@current_user_exists
def signin():
    form = SignInForm()
    if request.method == "POST" and form.validate():
        registered_bro = Bro.query.filter_by(email=form.email.data).first()

        if registered_bro and registered_bro.is_correct_password(form.password.data):
            flash("Bro logged in successfully", 'info')
            login_user(registered_bro, remember=form.remember.data)
            return redirect(url_for('bro.index'))

        flash("Email or Password is invalid.", "error")
        return redirect(url_for('bro.signin'))

    return render_template('bro/signin.html', form=form)


@bro.route('/signup', methods=['GET', 'POST'])
@current_user_exists
def signup():
    form = SignUpForm()
    if request.method == "POST" and form.validate_for_exist():
        bro_model = Bro(username=form.username.data,
                        password=form.password.data,
                        email=form.email.data,
                        birthdate=form.birthdate.data)
        db.session.add(bro_model)
        db.session.commit()
        flash('Bro has been successfully registered.', 'info')
        return redirect(url_for('bro.signin'))

    return render_template('bro/signup.html', form=form)


@bro.route('/signout')
@login_required
def signout():
    logout_user()
    flash("Bro logged out successfully", 'info')
    return redirect(url_for('bro.index'))


@bro.route("/profile")
@login_required
def profile():
    return render_template('bro/profile.html')


@bro.route("/profile/edit", methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditForm(request.form, obj=current_user)
    if request.method == "POST" and form.validate_for_exist(current_bro=current_user):
        form.populate_obj(current_user)
        db.session.commit()
        flash("You profile has been successfully updated.", "info")
    return render_template('bro/edit_profile.html', form=form)


@bro.route("/profile/delete", methods=['GET', 'POST'])
@login_required
def delete_profile():
    form = DeleteForm()
    if request.method == "POST" and form.validate():
        db.session.delete(current_user)
        db.session.commit()
        flash("You profile has been successfully deleted", "info")
        return redirect(url_for('bro.index'))
    return render_template('bro/delete_profile.html', form=form)


@bro.route("/bros")
def list_bros():
    page = abs(int(request.args.get('page', 1)))
    sort = str(request.args.get('sort', ''))

    sort_strategy = SortStrategy(strategy=sort)
    total, result = sort_strategy.get_result(page=page, per_page=BROS_PER_PAGE)

    pagination = Pagination(page=page, total=total,
                            search=False,
                            per_page=BROS_PER_PAGE,
                            css_framework='bootstrap3')

    return render_template('bro/list_bros.html', result=result, sort=sort, pagination=pagination)


@bro.route('/bros/<int:bro_id>')
def bro_profile(bro_id):
    bro_model = Bro.query.get(bro_id)
    if not bro_model:
        flash("Bro doesn't exist", 'error')
        return redirect(url_for('bro.list_bros'))
    return render_template('bro/bro_profile.html', bro=bro_model)


@bro.route('/bros/friend/<int:bro_id>')
@login_required
def friend_bro(bro_id):
    bro_model = Bro.query.get(bro_id)
    if not bro_model:
        flash("Bro doesn't exist", 'error')
        return redirect(redirect_url('bro.list_bros'))

    if current_user.id == bro_model.id:
        flash("Are you sure? :)", "error")
        return redirect(redirect_url('bro.list_bros'))

    current_user.befriend(bro_model)
    db.session.commit()
    flash("Bro has been successfully added as a friend", "info")
    return redirect(redirect_url('bro.list_bros'))


@bro.route("/bros/unfriend/<int:bro_id>")
@login_required
def unfriend_bro(bro_id):
    bro_model = Bro.query.get(bro_id)
    if not bro_model:
        flash("Bro doesn't exist", 'error')
        return redirect(redirect_url('bro.list_bros'))

    current_user.unfriend(bro_model)
    db.session.commit()
    flash("Bro has been successfully unfriended", "info")
    return redirect(redirect_url('bro.list_bros'))


@bro.route('/bros/best_friend/<int:bro_id>')
@login_required
def best_friend_bro(bro_id):
    bro_model = Bro.query.get(bro_id)

    if not bro_model:
        flash("Bro doesn't exist", 'error')
        return redirect(redirect_url('bro.list_bros'))

    if current_user.id == bro_model.id:
        flash("Are you sure? :)", "error")
        return redirect(redirect_url('bro.list_bros'))

    current_user.add_best_friend(bro_model)
    db.session.commit()
    flash("Bro has been successfully added as a best friend", "info")
    return redirect(redirect_url('bro.list_bros'))


@bro.route("/bros/remove_best_friend/<int:bro_id>")
@login_required
def remove_best_friend(bro_id):
    bro_model = Bro.query.get(bro_id)
    if not bro_model:
        flash("Bro doesn't exist", 'error')
        return redirect(redirect_url('bro.list_bros'))

    current_user.remove_best_friend(bro_model)
    db.session.commit()
    flash("Best Bro has been successfully unfriended", "info")
    return redirect(redirect_url('bro.list_bros'))

application/main/__init__.py
# -*- coding:utf-8 -*-

application/main/app.py
# -*- coding:utf-8 -*-
import os
from base import Base
from application.bro.models import AnonymousBro
from application.main.extensions import db, migrate, csrf_protect, login_manager
from application.bro.views import bro
from application.main.settings import config


class App(Base):
    def configure_database(self):
        db.app = self
        db.init_app(self)

    def configure_extensions(self):
        migrate.init_app(self, db)
        csrf_protect.init_app(self)

    def configure_login_manager(self):
        login_manager.init_app(self)
        login_manager.login_view = 'bro.signin'
        login_manager.anonymous_user = AnonymousBro


def app_factory(environment, app_name):
    app = App(app_name, template_folder='application/templates', static_folder='application/static')
    app.configure(config=config[environment])
    app.secret_key = os.urandom(24)
    app.add_blueprint_list((bro,))
    app.setup()
    return app

application/templates/bro/bro_profile.html
{% extends 'layouts/base.html' %}

{% set page_title = "Profile" %}

{% block container %}
    <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="text-center">
                <img src="{{ url_for('static', filename='images/no-user.jpg') }}"
                     class="avatar img-circle img-thumbnail" alt="avatar">
                <h6>Your profile photo</h6>
            </div>
        </div>
        <div class="col-md-8 col-xs-12">
            <div class="col-md-10">
                <h3>Personal info</h3>
                <table class="table">
                    <tr>
                        <td>Username</td>
                        <td>{{ bro }}</td>
                    </tr>
                    <tbody>
                    <tr>
                        <td>Age</td>
                        <td>{{ bro.age }} years old</td>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td><a href="mailto:{{ bro.email }}">{{ bro.email }}</a></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-md-8">
                {% if current_user.is_authenticated %}
                    <div>
                        {% if current_user.is_same_bro(bro) %}
                            <a href="{{ url_for('bro.edit_profile') }}" class="btn btn-primary">Edit Profile</a>
                            <span></span>
                            <a href="{{ url_for('bro.delete_profile') }}" class="btn btn-danger">Delete Profile</a>
                        {% elif current_user.is_friend(bro) %}
                            <a class="btn btn-danger"
                               href="{{ url_for('bro.unfriend_bro', bro_id=bro.id) }}">
                                <i class="fa fa-user"></i>
                                Unfriend
                            </a>
                        {% else %}
                            {% if current_user.best_friend and current_user.best_friend.id == bro.id %}
                                <a class="btn btn-danger"
                                   href="{{ url_for('bro.remove_best_friend', bro_id=bro.id) }}">
                                    <i class="fa fa-user"></i>
                                    Delete Best Friend
                                </a>
                            {% else %}
                                {% if not current_user.best_friend %}
                                    <a class="btn btn-primary"
                                       href="{{ url_for('bro.best_friend_bro', bro_id=bro.id) }}">
                                        <i class="fa fa-user"></i>
                                        Make Best Friend
                                    </a>
                                {% endif %}
                                <a class="btn btn-info"
                                   href="{{ url_for('bro.friend_bro', bro_id=bro.id) }}">
                                    <i class="fa fa-user"></i>
                                    Add Friend
                                </a>
                            {% endif %}
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

application/templates/bro/delete_profile.html
{% extends 'layouts/base.html' %}

{% set page_title = "Delete Profile" %}

{% block container %}
    <div class="row">
        <div class="col-md-8 col-xs-12">
            <div class="col-md-12">
                <form class="form-horizontal" method="post" action="{{ url_for('bro.delete_profile') }}" role="form">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        <div class="cols-sm-10">
                            <div class="input-group">
                                <p>Are you sure to delete your profile?</p>
                            </div>
                        </div>
                    </div>

                    <div class="form-group ">
                        <button type="submit" class="btn btn-danger">Delete Profile</button>
                        <span></span>
                        <a href="{{ url_for('bro.profile') }}" class="btn btn-default">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

application/templates/bro/edit_profile.html
{% extends 'layouts/base.html' %}

{% set page_title = "Edit Profile" %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker3.min.css') }}">
{% endblock %}


{% block container %}
    <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="text-center">
                <img src="{{ url_for('static', filename='images/no-user.jpg') }}"
                     class="avatar img-circle img-thumbnail" alt="avatar">
                <h6>Your profile photo</h6>
            </div>
        </div>
        <div class="col-md-8 col-xs-12">
            <div class="col-md-12">
                <form class="form-horizontal" method="post" action="{{ url_for('bro.edit_profile') }}" role="form">
                    {{ form.csrf_token }}
                    <div class="form-group {% if form.username.errors %} has-error {% endif %}">
                        {{ form.username.label(class_="col-lg-3 control-label") }}
                        <div class="col-lg-8">
                            {{ form.username(class_="form-control") }}
                            {% for error in form.username.errors %}
                                <p class="help-block">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group {% if form.email.errors %} has-error {% endif %}">
                        {{ form.email.label(class_="col-lg-3 control-label") }}
                        <div class="col-lg-8">
                            {{ form.email(class_="form-control") }}
                            {% for error in form.email.errors %}
                                <p class="help-block">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group {% if form.birthdate.errors %} has-error {% endif %}">
                        {{ form.birthdate.label(class_="col-lg-3 control-label") }}
                        <div class="col-lg-8">
                            {{ form.birthdate(class_="form-control", id='birthdate') }}
                            {% for error in form.birthdate.errors %}
                                <p class="help-block">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label"></label>
                        <div class="col-md-8">
                            <input class="btn btn-primary" value="Save Changes" type="submit">
                            <span></span>
                            <a href="{{ url_for('bro.profile') }}" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        $(function () {
            $('#birthdate').datepicker({
                endDate: '-10y'
            });
        });
    </script>
{% endblock %}

application/templates/bro/index.html
{% extends 'layouts/base.html' %}

{% set page_title = "Home" %}

{% block container %}
    <div class="row text-center">
        <h1>Bro Social Network</h1>
        <p class="lead">
            Welcome to the Bro Social Network. Connect with your Bros and enjoy your time.
        </p>
    </div>
{% endblock %}

application/templates/bro/list_bros.html
{% extends 'layouts/base.html' %}

{% set page_title = "List Bros" %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/data-tables.bootstrap.min.css') }}">
{% endblock %}

{% set bro_name_class = 'sorting' %}
{% if sort == 'name_asc' %}
    {% set bro_name_class = 'sorting_asc' %}
{% elif sort == 'name_desc' %}
    {% set bro_name_class = 'sorting_desc' %}
{% endif %}

{% set friends_name_class = 'sorting' %}
{% if sort == 'friends_qty_asc' %}
    {% set friends_name_class = 'sorting_asc' %}
{% elif sort == 'friends_qty_desc' %}
    {% set friends_name_class = 'sorting_desc' %}
{% endif %}

{% set best_friend_name_class = 'sorting' %}
{% if sort == 'best_friend_asc' %}
    {% set best_friend_name_class = 'sorting_asc' %}
{% elif sort == 'best_friend_desc' %}
    {% set best_friend_name_class = 'sorting_desc' %}
{% endif %}

{% block container %}
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered dataTable">
                <thead>
                <tr>
                    <th class="sortable {{ bro_name_class }}" id="name">
                        Bro name
                    </th>
                    <th class="sortable {{ best_friend_name_class }}" id="best_friend">Best Friend</th>
                    <th class="sortable {{ friends_name_class }}" id="friends_qty">Friends</th>
                    {% if current_user.is_authenticated %}
                        <th width="220">Actions</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for bro in result %}
                    <tr>
                        <td>
                            <a href="{{ url_for('bro.bro_profile', bro_id=bro.id) }}">{{ bro.username }}</a>
                        </td>
                        <td>
                            {% if bro.best_friend %}
                                <a href="{{ url_for('bro.bro_profile', bro_id=bro.best_friend.id) }}">{{ bro.best_friend }}</a>
                            {% endif %}
                        </td>
                        <td class="text-center">{{ bro.friends_qty }}</td>
                        {% if current_user.is_authenticated %}
                            <td>
                                <div>
                                    {% if current_user.is_same_bro(bro) %}
                                        <span class="label label-success">You</span>
                                    {% elif current_user.is_friend(bro) %}
                                        <a class="btn btn-danger btn-xs"
                                           href="{{ url_for('bro.unfriend_bro', bro_id=bro.id) }}">
                                            <i class="fa fa-user"></i>
                                            Unfriend
                                        </a>
                                    {% else %}
                                        {% if current_user.best_friend and current_user.best_friend.id == bro.id %}
                                            <a class="btn btn-success btn-xs"
                                               href="{{ url_for('bro.remove_best_friend', bro_id=bro.id) }}">
                                                <i class="fa fa-user"></i>
                                                Delete Best Friend
                                            </a>
                                        {% else %}
                                            {% if not current_user.best_friend %}
                                                <a class="btn btn-primary btn-xs"
                                                   href="{{ url_for('bro.best_friend_bro', bro_id=bro.id) }}">
                                                    <i class="fa fa-user"></i>
                                                    Make Best Friend
                                                </a>
                                            {% endif %}
                                            <a class="btn btn-info btn-xs"
                                               href="{{ url_for('bro.friend_bro', bro_id=bro.id) }}">
                                                <i class="fa fa-user"></i>
                                                Add Friend
                                            </a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </td>
                        {% endif %}
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4" class="text-center">
                            There are any bros in the Bro Social Network.
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <form id="sortable" method="get">
                <input name="page" value="{{ pagination.page }}" type="hidden">
                <input name="sort" id="sort" type="hidden">
            </form>
        </div>
    </div>
    {{ pagination.links }}
{% endblock %}

{% block js %}
    {{ super() }}
    <script>
        $(function () {
            var sort_strategy = '_asc';
            $('.sortable').on('click', function () {
                var id = $(this).attr('id');
                if ($(this).hasClass('sorting_asc')) {
                    sort_strategy = '_desc';
                }

                var sort = id + sort_strategy;
                $('#sort').attr('value', sort);
                $('#sortable').submit();
            });
        });
    </script>
{% endblock %}

application/templates/bro/profile.html
{% extends 'layouts/base.html' %}

{% set page_title = "Profile" %}

{% block container %}
    <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="text-center">
                <img src="{{ url_for('static', filename='images/no-user.jpg') }}"
                     class="avatar img-circle img-thumbnail" alt="avatar">
                <h6>Your profile photo</h6>
            </div>
        </div>
        <div class="col-md-8 col-xs-12">
            <div class="col-md-10">
                <h3>Personal info</h3>
                <table class="table">
                    <tr>
                        <td>Username</td>
                        <td>{{ current_user }}</td>
                    </tr>
                    <tbody>
                    <tr>
                        <td>Age</td>
                        <td>{{ current_user.age }} years old</td>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td><a href="mailto:{{ current_user.email }}">{{ current_user.email }}</a></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-md-8">
                <a href="{{ url_for('bro.edit_profile') }}" class="btn btn-primary">Edit Profile</a>
                <span></span>
                <a href="{{ url_for('bro.delete_profile') }}" class="btn btn-danger">Delete Profile</a>
            </div>
        </div>
    </div>
{% endblock %}

application/templates/bro/signin.html
{% extends 'layouts/base.html' %}

{% set page_title = "Sign In" %}

{% block container %}
    <div class="row">
        <div class="main-login main-center">
            <h3>Sign In</h3>
            <form id="signinForm" class="form-horizontal" method="post" role="form"
                  action="{{ url_for('bro.signin') }}">
                {{ form.csrf_token }}
                <div class="form-group {% if form.email.errors %} has-error {% endif %}">
                    {{ form.email.label(class_="cols-sm-2 control-label") }}
                    <div class="cols-sm-10">
                        <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-user fa" aria-hidden="true"></i>
                                </span>
                            {{ form.email(placeholder="Enter your Email", class_="form-control") }}
                        </div>
                    </div>
                    {% for error in form.email.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                <div class="form-group {% if form.password.errors %} has-error {% endif %}">
                    {{ form.password.label(class_="cols-sm-2 control-label") }}
                    <div class="cols-sm-10">
                        <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-lock fa" aria-hidden="true"></i>
                                </span>
                            {{ form.password(placeholder="Enter your Password", class_="form-control") }}
                        </div>
                    </div>
                    {% for error in form.password.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            {{ form.remember(class_="") }}
                            {{ form.remember.label.text | e }}
                        </label>
                    </div>
                </div>
                <div class="form-group ">
                    <button type="submit" class="btn btn-primary btn-block login-button">Sign In</button>
                </div>
                <div class="login-register">
                    <a href="{{ url_for('bro.signup') }}">Sign Up</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}